language: cpp

compiler: gcc

before_script:
    - mkdir build
    - cd build
    - cmake ..
      
script: make

addons:
    apt:
      packages:
        - cmake
      sources:
        - kalakris-cmake