  language: cpp
  matrix:
    include:
      # Works on Precise and Trusty
      - os: linux
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - g++-6
        env:
          - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

  before_install:
    - eval "${MATRIX_EVAL}"

  before_script:
      - mkdir build
      - cd build
      - cmake ..

  script: 
      - make
      - cd ..
      - ./deploy-test-script.sh 5 2000 1 50.5 2000
      - ./deploy-test-script.sh 1000 200 1000 5 1

  after_success:
     - cd build
     - ./nasteroids 0 0
     - ./nasteroids 0 0 0 0 0
     - ./nasteroids 1 2 3 4.65 876
     - ./nasteroids a 4 as 3 d

  notifications:
    email: false
    slack: lavendiciondevs:cdzfkpSMhUov1iMl6z1CiIs1#arcos
