  language: generic
  matrix:
    include:
      - os: linux
        env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
        addons:
          apt:
            packages:
              - g++-5
            sources: &sources
              - llvm-toolchain-precise-3.8
              - ubuntu-toolchain-r-test
      - os: linux
        env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
        addons:
          apt:
            packages:
              - clang-3.8
            sources: *sources

  before_script:
      - mkdir build
      - cd build
      - cmake ..

  script: make

  after_success:
     - ./nasteroids 0 0
     - ./nasteroids 0 0 0 0 0
     - ./nasteroids 1 2 3 4.65 876
     - ./nasteroids a 4 as 3 d

     # Test that the values are equal than the base ones
     - ./nasteroids 5 2 1 50.5 2000
     - cat out.txt
     - cd ..
     - ./nasteroid-base 5 2 1 50.5 2000
     - diff init_conf.txt build/init.conf.txt
     - diff out.txt build/out.txt

  notifications:
    slack: lavendiciondevs:cdzfkpSMhUov1iMl6z1CiIs1#arcos
